sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 1JjdKdfRSQNEC7UoKyQQt6HORPyr/8ukS2Ay0H9O+LAKKjiYR26fEvzfEJNKYtyj1m2shlsun4OzoL51l80v9xRbPE9btrIeu4t9ySHmPRNxiFiFcyn8AU+bmcOQFmduTsRdme3YdjNKGLlMsVyWmaXL6zTB3MSig+rONMvzlwnKI67HJxCKK5njtIFer+cgq+4gI+c0Qy198HqxfGeVnjKetjSGlmGDkMinIk1ZE3Pfwy7NCzkXajABKJzeUwqcMG5TgMYNZXSZ1bSHlxPqWKkEjZUwHjtmyquXh55aW/tGYk4Bhsl4qzZYFNhLiTnKj4UmGg5X6OAkZdsyQij8a4ph0aV+T7N8UT8KAJ2CRR/0tMrzo14uB5qCFprEJDap3UN4r2S12CjoZb5IXF7GDi4/NN524Kklb22JScysCKxt8c8+1AP3EQNsSK6SsF9gZzdRoBWj4jtskzEGoNaZLGkrLUoBorn39AaPlJeZsOjbDQ+sF6r0L2fNud7M9kWJhXGfEMxh8RgnpiamKynSNti/hHse2tIl8oOhA5yo0il3nEkKeHNt4VikIoW0Ox3nVB91ydE+xSIRwCtUmc+WHxV9mLUk4+KiaO9/1aE67jBl4H47i3nArirQvOoFVCsRUTnBYyqqZX+emJemXjcnQKTO2LLnLvZar+XRN59xI8s=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Wacousta---a-tale-of-the-Pontiac-conspiracy---Volume-3_4911
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy